# Load data

install.packages("Seurat")
BiocManager::install("BiocSingular")
BiocManager::install("scDblFinder")
BiocManager::install("SingleCellExperiment")
BiocManager::install("SingleR")
BiocManager::install("scater")
library(Seurat)
library(data.table)
library(ggplot2)
library(dplyr)
library(BiocSingular)
library(scDblFinder)
library(SingleCellExperiment)
library(SingleR)
library(scater)

covid_nbt_main <- readRDS("data/covid_sub10.rds")
viral_load <- readxl::read_excel("/net/pupil1/home/people/s223102/scRNAseq/a6fb8098-7a58-45e6-884e-f25b1cdb94dd/ViralRNA_CPM.xlsx")
